name: foodish_app
description: A food image viewer app using the Foodish API

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# This section is optional if you are using assets or images
assets:
  - assets/images/
